OC.L10N.register(
    "auto_groups",
    {
    "Auto Groups" : "Automatické skupiny",
    "Automatically adds all users to one or multiple specified groups." : "Automaticky přidá všechny uživatele do jedné či více zadaných skupin.",
    "Automatically add users to the specified Auto Groups, except those users belonging to one of the specified Override Groups. \nOptionally, the group assignment can be triggered on every successful login, which is useful for external user backends.\n\n## Configuration\n\n- Go to \"Admin Settings > Additional Settings\"\n- Configure the Auto Groups\n- If required, configure the Override Groups (e.g., for Service Accounts)\n- Optionally, enable the Login Hook, which will enforce correct group membership on every successful login" : "Uživatele automaticky přidat do zadaných skupin, s výjimkou těch uživatelů, kteří jsou členy jedné nebo více zadaných přepisujících skupin.\nVolitelně, přiřazení skupiny je možné spouštět po každém úspěšném přihlášení, což se hodí pro uživatele z externích systémů.\n\n## Nastavení\n\n- Jděte do „Nastavení správy > Další nastavení“\n- Nastavení Automatických skupin\n- Pokud je požadováno, nastavte Přepisující skupiny (např., pro Servisní účty)\n- Volitelně, zapněte Přihlašovací háčky, které vynutí správné členství ve skupinách při každém úspěšném přihlášení",
    "Auto Groups:" : "Automatické skupiny:",
    "Automatically add all users to these groups." : "Automaticky přidat všechny uživatele do těchto skupin.",
    "Override Groups:" : "Přepsat skupiny:",
    "Users which are member of at least one of these groups are removed from the auto groups. This is also the case if the user is added to one of these groups after creation, i.e., membership in the override groups is checked after each group modification." : "Uživatelé, kteří jsou členy alespoň jedné z těchto skupin jsou odebráni z automatických skupin. Toto je také případ, pokud je uživatel přidán do jedné z těchto skupin po vytvoření, tj. členství v přepisujících skupinách je kontrolováno pro každé změně ve skupině.",
    "Check for correct Auto Group membership on every login." : "Kontrolovat správnost členství v automatických skupinách při každém přihlášení.",
    "Enable this setting to enforce proper Auto Group membership on every successful login. This is useful if either users are not created in Nextcloud (e.g., with external user backends) or to enforce correct group membership for all users when the Auto Groups / Override Groups have changed." : "Toto nastavení zapněte pro vynucení správného členství v automatických skupinách při každém úspěšném přihlášení. Toto se hodí pokud uživatel buďto není vytvořený v Nextcloud (např. v případě uživatelů z externích systémů) nebo pro vynucení správného členství ve skupinách pro všechny uživatele, když se automatické / přepisující skupiny změní."
},
"nplurals=4; plural=(n == 1 && n % 1 == 0) ? 0 : (n >= 2 && n <= 4 && n % 1 == 0) ? 1: (n % 1 != 0 ) ? 2 : 3;");
