OC.L10N.register(
    "auto_groups",
    {
    "Group \"%1$s\" is used in the Auto Groups App and cannot be deleted." : "그룹 \"%1$s\"은 Auto Groups App에서 사용되므로 삭제할 수 없습니다.\n ",
    "Auto Groups" : "자동 그룹",
    "Automatically adds all users to one or multiple specified groups." : "지정된 하나 이상의 그룹에 모든 사용자를 자동으로 추가합니다.",
    "Automatically add users to the specified Auto Groups, except those users belonging to one of the specified Override Groups. \nOptionally, the group assignment can be triggered on every successful login, which is useful for external user backends.\n\n## Configuration\n\n- Go to \"Settings > Administration > Additional settings\"\n- Configure the Auto Groups\n- If required, configure the Override Groups (e.g., for Service Accounts)\n- Optionally, enable the Login Hook, which will enforce correct group membership on every successful login\n\nNote that this app prevents group deletions for groups referenced as Auto Groups or Override Groups.\n\n## Comparison to similar Apps\n\n* [Everyone Group](https://apps.nextcloud.com/apps/group_everyone): The \"Everyone Group\" app adds a virtual Group Backend, always returning all users. In contrast, \"Auto Groups\" operates on \"real\" groups in your normal Group Backend. Additionally, it is possible to specify Override Groups which will prevent users from being added to the Auto Group(s).\n* [Default Group](https://apps.nextcloud.com/apps/defaultgroup): \"Auto Groups\" is actually a modernized and maintaned fork of \"Default Group\", which seems to be abandoned since NC12 or so. In terms of functionality, they are almost identical.\n\nIn addition, I plan to add some more features over time, e.g., \"Union Groups\" - see the [Milestone Plans](https://github.com/stjosh/auto_groups/milestones) for more details." : "지정된 재정의 그룹 중 하나에 속한 사용자를 제외한 사용자를 지정된 자동 그룹에 자동으로 추가합니다.\n선택적으로 모든 로그인 성공 시 그룹 할당을 트리거할 수 있으며, 이는 외부 사용자 백엔드에 유용합니다.\n\n## 구성\n\n- \"관리 설정 > 추가 설정\"으로 이동합니다.\n- 자동 그룹 구성\n- 필요한 경우 그룹 재정의(예: 서비스 계정)를 구성합니다.\n- 선택적으로 로그인 후크를 사용하도록 설정합니다. 로그인에 성공할 때마다 올바른 그룹 구성원 자격을 적용합니다.\n\n이 앱은 자동 그룹 또는 그룹 재정의로 참조되는 그룹에 대한 그룹 삭제를 방지합니다.\n\n## 유사 앱과의 비교\n\n* [모두 그룹](https://apps.nextcloud.com/apps/group_everyone): \"Everyone Group\" 앱은 가상 그룹 백엔드를 추가하여 항상 모든 사용자를 반환합니다. 반대로, \"자동 그룹\"은 일반 그룹 백엔드의 \"실제\" 그룹에서 작동합니다. 또한 사용자를 Auto Group에 추가하지 못하도록 Override Groups를 지정할 수 있습니다.\n* [기본 그룹](https://apps.nextcloud.com/apps/defaultgroup): '오토그룹'은 사실상 NC12 이후 버려지는 듯한 '디폴트그룹'의 현대화·유지보수 포크입니다. 기능적인 면에서는 거의 동일합니다.\n\n또한 시간이 지남에 따라 \"Union Groups\"(유니온 그룹)와 같은 몇 가지 기능을 추가할 계획입니다. 자세한 내용은 [Milestone Plans](https://github.com/stjosh/auto_groups/milestones)을 참조하십시오.",
    "Automatically add all users to these groups." : "모든 사용자를 이러한 그룹에 자동으로 추가합니다.",
    "Override Groups:" : "그룹 재정의:",
    "Users which are member of at least one of these groups are removed from the auto groups. This is also the case if the user is added to one of these groups after creation, i.e., membership in the override groups is checked after each group modification." : "이러한 그룹 중 하나 이상의 구성원인 사용자는 자동 그룹에서 제거됩니다. 이는 사용자가 생성 후 이러한 그룹 중 하나에 추가되는 경우에도 마찬가지입니다. 즉, 재정의 그룹의 구성원 자격이 각 그룹 수정 후 검사됩니다.",
    "Set Auto Group membership on user creation." : "사용자 생성 시 Auto Group 구성원 자격을 설정합니다.",
    "If checked, Auto Group membership will be enforced on user creation." : "이 옵션을 선택하면 사용자 생성 시 Auto Group 구성원 자격이 적용됩니다.",
    "Check Auto Group membership on modification of a user's groups." : "사용자의 그룹을 수정하기 위해서는 Auto Group 구성원 자격을 확인해 주세요.",
    "If checked, Auto Group membership will be re-enforced for a user account every time it is added to or removed from a group." : "이 옵션을 선택하면, 사용자 계정이 그룹에 추가되거나 삭제될 때마다 Auto Group 구성원 자격이 다시 적용됩니다.",
    "Check for correct Auto Group membership on every login." : "로그인할 때마다 Auto Group 구성원 자격이 올바른지 확인합니다.",
    "Enable this setting to enforce proper Auto Group membership on every successful login. This is useful if either users are not created in Nextcloud (e.g., with external user backends) or to enforce correct group membership for all users when the Auto Groups / Override Groups have changed." : "로그인에 성공할 때마다 적절한 Auto Group 구성원 자격을 적용하려면 이 설정을 사용합니다. 이 기능은 사용자가 Next Cloud에서 생성되지 않았거나(예: 외부 사용자 백엔드 포함) Auto Groups/Override Groups(자동 그룹/Override Groups(그룹 재정의)가 변경되었을 때 모든 사용자에게 올바른 그룹 구성원 자격을 적용하는 경우에 유용합니다."
},
"nplurals=1; plural=0;");
