OC.L10N.register(
    "auto_groups",
    {
    "Group \"%1$s\" is used in the Auto Groups App and cannot be deleted." : "Skupina „%1$s“ sa používa v aplikácii Automatické skupiny a nedá sa odstrániť.",
    "Auto Groups" : "Automatické skupiny",
    "Automatically adds all users to one or multiple specified groups." : "Automaticky pridá všetkých používateľov do jednej alebo viacerých určených skupín.",
    "Automatically add users to the specified Auto Groups, except those users belonging to one of the specified Override Groups. \nOptionally, the group assignment can be triggered on every successful login, which is useful for external user backends.\n\n## Configuration\n\n- Go to \"Admin Settings > Additional Settings\"\n- Configure the Auto Groups\n- If required, configure the Override Groups (e.g., for Service Accounts)\n- Optionally, enable the Login Hook, which will enforce correct group membership on every successful login\n\nNote that this app prevents group deletions for groups referenced as Auto Groups or Override Groups.\n\n## Comparison to similar Apps\n\n* [Everyone Group](https://apps.nextcloud.com/apps/group_everyone): The \"Everyone Group\" app adds a virtual Group Backend, always returning all users. In contrast, \"Auto Groups\" operates on \"real\" groups in your normal Group Backend. Additionally, it is possible to specify Override Groups which will prevent users from being added to the Auto Group(s).\n* [Default Group](https://apps.nextcloud.com/apps/defaultgroup): \"Auto Groups\" is actually a modernized and maintaned fork of \"Default Group\", which seems to be abandoned since NC12 or so. In terms of functionality, they are almost identical.\n\nIn addition, I plan to add some more features over time, e.g., \"Union Groups\" - see the [Milestone Plans](https://github.com/stjosh/auto_groups/milestones) for more details." : "Automaticky pridáva používateľov do určených automatických skupín, s výnimkou používateľov patriacich do jednej z prepisujúcich skupín.\nPriradenie skupiny je možné spustiť pri každom úspešnom prihlásení, čo je užitočné pre externé služby.\n\n## Nastavenie\n\n- Prejdite na „Nastavenia správcu > Ďalšie nastavenia“\n- Nastavte automatické skupiny\n- Ak je to potrebné, nastavte prepisujúce skupiny (napr. Pre účty služieb).\n- Voliteľne povoľte prihlasovaciu kotvu, ktorá pri každom úspešnom prihlásení vynúti správne členstvo v skupine\n\nPamätajte, že táto aplikácia zabraňuje vymazaniu skupín, ktoré sa odkazujú na automatické alebo prepisujúce skupiny.\n\n## Porovnanie s podobnými aplikáciami\n\n* [Skupina Všetci](https://apps.nextcloud.com/apps/group_everyone): Aplikácia „Skupina Všetci]“ pridá virtuálnu službu skupiny, ktorá vracia všetkých používateľov. Naproti tomu „Automatické skupiny“ pracujú so „skutočnými“ skupinami vo vaše normálnej službe Skupiny. Ďalej je možné určiť prepisujúce skupiny, ktoré zabránia používateľom pridať sa do automatických skupín.\n* [Predvolená skupina] (https://apps.nextcloud.com/apps/defaultgroup): „Automatické skupiny“ je vlastne modernizované a udržiavané pokračovanie „Predvolené skupina“, ktorá sa zdá byť opustená približne od  NC12. Z hľadiska funkčnosti sú takmer rovnaké.\n\nOkrem toho plánujem postupnepridať ďalšie funkcie, napríklad „Skupiny odborov“ - ďalšie podrobnosti nájdete v [Milestone Plans](https://github.com/stjosh/auto_groups/milestones).",
    "Automatically add all users to these groups." : "Automaticky pridávať všetkých používateľov do týchto skupín.",
    "Override Groups:" : "Prepisujúce skupiny:",
    "Users which are member of at least one of these groups are removed from the auto groups. This is also the case if the user is added to one of these groups after creation, i.e., membership in the override groups is checked after each group modification." : "Používatelia, ktorí sú členmi aspoň jednej z týchto skupín, sú odstránení z automatických skupín. To je tiež prípad, keď je užívateľ pridaný do jednej z týchto skupín po vytvorení, t.j. členstvo v prepisujúcich skupinách sa kontroluje po každej zmene skupiny.",
    "Check for correct Auto Group membership on every login." : "Kontrolovať správnosť členstva v automatických skupinách pri každom prihlásení.",
    "Enable this setting to enforce proper Auto Group membership on every successful login. This is useful if either users are not created in Nextcloud (e.g., with external user backends) or to enforce correct group membership for all users when the Auto Groups / Override Groups have changed." : "Povoľte toto nastavenie, aby ste pri každom úspešnom prihlásení vynútili správne členstvo v automatickej skupine. Toto je užitočné, ak nie je používateľ vytvorený v Nextcloud (napr. prípade používateľov z externých systémov), alebo pre vynútenie správneho členstva v skupinách pre všetkých používateľov, keď sa zmenili automatické/prepisujúce skupiny."
},
"nplurals=4; plural=(n % 1 == 0 && n == 1 ? 0 : n % 1 == 0 && n >= 2 && n <= 4 ? 1 : n % 1 != 0 ? 2: 3);");
