OC.L10N.register(
    "auto_groups",
    {
    "Group \"%1$s\" is used in the Auto Groups App and cannot be deleted." : "Група „%1$s” се користи у апликацији Аутоматских група и не може да се обрише.",
    "Auto Groups" : "Аутоматске групе",
    "Automatically adds all users to one or multiple specified groups." : "Аутоматски додај све корисније у једну или више одабраних група.",
    "Automatically add users to the specified Auto Groups, except those users belonging to one of the specified Override Groups. \nOptionally, the group assignment can be triggered on every successful login, which is useful for external user backends.\n\n## Configuration\n\n- Go to \"Admin Settings > Additional Settings\"\n- Configure the Auto Groups\n- If required, configure the Override Groups (e.g., for Service Accounts)\n- Optionally, enable the Login Hook, which will enforce correct group membership on every successful login\n\nNote that this app prevents group deletions for groups referenced as Auto Groups or Override Groups.\n\n## Comparison to similar Apps\n\n* [Everyone Group](https://apps.nextcloud.com/apps/group_everyone): The \"Everyone Group\" app adds a virtual Group Backend, always returning all users. In contrast, \"Auto Groups\" operates on \"real\" groups in your normal Group Backend. Additionally, it is possible to specify Override Groups which will prevent users from being added to the Auto Group(s).\n* [Default Group](https://apps.nextcloud.com/apps/defaultgroup): \"Auto Groups\" is actually a modernized and maintaned fork of \"Default Group\", which seems to be abandoned since NC12 or so. In terms of functionality, they are almost identical.\n\nIn addition, I plan to add some more features over time, e.g., \"Union Groups\" - see the [Milestone Plans](https://github.com/stjosh/auto_groups/milestones) for more details." : "Аутоматски додајте кориснике у одабране групе, осим оних корисника који припадају одређеним групама.\nОпционо, додавање у групу се може окинути да се деси после сваке успешне пријаве, што може бити корисно за спољне моторе пријава.\n\n## Поставке\n\n- Уђите у „Администрација > Додатне поставке”\n- Подесите аутоматске групе\n- Ако је потребно, подесите неважеће групе (нпр. за сервисне налоге)\n- Опционо, омогућите окидач на пријаву, који ће наметнути чланство у исправне групе након сваке успешне пријаве\n\nОва апликација ће спречити брисање група које се помињу у аутоматским групама или међу неважећим групама.\n\n## Поређење са сличним апликацијама\n\n* [Everyone Group](https://apps.nextcloud.com/apps/group_everyone): „Everyone Group” апликација додаје виртуални позадински мотор за групе, који увек враћа све кориснике. У поређењу са тим, „Аутоматске групе” раде са „стварним” групама у нормланом позадинском мотору за групе. Додатно, могуће је навести неважеће групе, за које корисници неће бити додати у аутоматске групе.\n* [Default Group](https://apps.nextcloud.com/apps/defaultgroup): „Аутоматске групе” су заправо модернизована и одржавана верзија „Подразумеваних група” које су изгледа напуштене од Некстклауда 12. Што се тиче функционалности, скоро су идентичне.\n\nКао додатак, планирам да додам још неке функционалности временом, нпр. „Унија група” - видите [Milestone Plans](https://github.com/stjosh/auto_groups/milestones) за више детаља.",
    "Auto Groups:" : "Аутоматске групе:",
    "Automatically add all users to these groups." : "Аутоматски додај све кориснике у ове групе.",
    "Override Groups:" : "Неважеће групе:",
    "Users which are member of at least one of these groups are removed from the auto groups. This is also the case if the user is added to one of these groups after creation, i.e., membership in the override groups is checked after each group modification." : "Корисници који су чланови бар једне од ових група се уклоњени из аутоматских група. Ово је случај и ако се корисник дода у неку од ових група накнадно, тј. чланство у неважећим групама се проверавам после сваке измене групе.",
    "Check for correct Auto Group membership on every login." : "Провери исправно чланство у аутоматским групама приликом сваке пријаве.",
    "Enable this setting to enforce proper Auto Group membership on every successful login. This is useful if either users are not created in Nextcloud (e.g., with external user backends) or to enforce correct group membership for all users when the Auto Groups / Override Groups have changed." : "Укључите ово да наметнете чланство у аутоматске групе на сваку успешну пријаву. Ово је корисно или ако се корисници не креирају из Некстклауда (нпр. са спољним позадинском мотором за кориснике) или да наметне чланство за све кориснике ако/кад се аутоматске групе или неважеће групе промене."
},
"nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2);");
