OC.L10N.register(
    "auto_groups",
    {
    "Group \"%1$s\" is used in the Auto Groups App and cannot be deleted." : "گۇرۇپپا «% 1 $ s» ئاپتوماتىك گۇرۇپپا دېتالىدا ئىشلىتىلىدۇ ، ئۇنى ئۆچۈرگىلى بولمايدۇ.",
    "Auto Groups" : "ئاپتوماتىك گۇرۇپپىلار",
    "Automatically adds all users to one or multiple specified groups." : "بارلىق ئىشلەتكۈچىلەرنى بىر ياكى بىر قانچە ئالاھىدە گۇرۇپپىغا ئاپتوماتىك قوشىدۇ.",
    "Automatically add users to the specified Auto Groups, except those users belonging to one of the specified Override Groups. \nOptionally, the group assignment can be triggered on every successful login, which is useful for external user backends.\n\n## Configuration\n\n- Go to \"Settings > Administration > Additional settings\"\n- Configure the Auto Groups\n- If required, configure the Override Groups (e.g., for Service Accounts)\n- Optionally, enable the Login Hook, which will enforce correct group membership on every successful login\n\nNote that this app prevents group deletions for groups referenced as Auto Groups or Override Groups.\n\n## Comparison to similar Apps\n\n* [Everyone Group](https://apps.nextcloud.com/apps/group_everyone): The \"Everyone Group\" app adds a virtual Group Backend, always returning all users. In contrast, \"Auto Groups\" operates on \"real\" groups in your normal Group Backend. Additionally, it is possible to specify Override Groups which will prevent users from being added to the Auto Group(s).\n* [Default Group](https://apps.nextcloud.com/apps/defaultgroup): \"Auto Groups\" is actually a modernized and maintaned fork of \"Default Group\", which seems to be abandoned since NC12 or so. In terms of functionality, they are almost identical.\n\nIn addition, I plan to add some more features over time, e.g., \"Union Groups\" - see the [Milestone Plans](https://github.com/stjosh/auto_groups/milestones) for more details." : "كۆرسىتىلگەن ئاپتوماتىك گۇرۇپپىلارغا تەۋە بولغان ئىشلەتكۈچىلەردىن باشقا ، كۆرسىتىلگەن ئاپتوماتىك گۇرۇپپىلارغا ئاپتوماتىك قوشۇلىدۇ. \nئىختىيارىي ھالدا ، گۇرۇپپا تاپشۇرۇقنى ھەر بىر مۇۋەپپەقىيەتلىك كىرىشتە قوزغىتىشقا بولىدۇ ، بۇ سىرتقى ئىشلەتكۈچى ئارقا سەھنىسىگە پايدىلىق.\n\n## سەپلىمىسى\n\n- «تەڭشەكلەر> باشقۇرۇش> قوشۇمچە تەڭشەكلەر» گە كىرىڭ\n- ئاپتوماتىك گۇرۇپپىلارنى سەپلەڭ\n- ئەگەر ئېھتىياجلىق بولسا ، قاپلاش گۇرۇپپىسىنى سەپلەڭ (مەسىلەن ، مۇلازىمەت ھېساباتى ئۈچۈن)\n- ئىختىيارىي ھالدا ، كىرىش ئىلتىماسىنى قوزغىتىڭ ، ئۇ ھەر بىر مۇۋەپپەقىيەتلىك كىرىشتە توغرا گۇرۇپپا ئەزالىقىنى ئىجرا قىلىدۇ\n\nشۇنىڭغا دىققەت قىلىڭكى ، بۇ ئەپ ئاپتوماتىك گۇرۇپپا ياكى گۇرۇپپىلارنى قاپلاش دەپ ئاتالغان گۇرۇپپىلارنىڭ گۇرۇپپا ئۆچۈرۈلۈشىنىڭ ئالدىنى ئالىدۇ.\n\n## مۇشۇنىڭغا ئوخشاش ئەپلەرگە سېلىشتۇرۇش\n\n* [ھەممە گۇرۇپپا] بۇنىڭغا سېلىشتۇرغاندا ، «ئاپتوماتىك گۇرۇپپىلار» نورمال گۇرۇپپا ئارقا سەھنىسىدىكى «ھەقىقىي» گۇرۇپپىلاردا مەشغۇلات قىلىدۇ. بۇنىڭدىن باشقا ، Override گۇرۇپپىلىرىنى بەلگىلىگىلى بولىدۇ ، بۇ ئابونتلارنىڭ ئاپتوماتىك گۇرۇپپا (لار) غا قوشۇلۇشىنىڭ ئالدىنى ئالىدۇ.\n* [كۆڭۈلدىكى گۇرۇپپى] ئىقتىدار جەھەتتە ، ئۇلار ئاساسەن ئوخشاش.\n\nئۇنىڭدىن باشقا ، مەن ۋاقىتنىڭ ئۆتۈشىگە ئەگىشىپ يەنە بىر قىسىم ئىقتىدارلارنى قوشۇشنى پىلانلاۋاتىمەن ، مەسىلەن ، «بىرلەشمە گۇرۇپپىلار» - تېخىمۇ كۆپ تەپسىلاتلار ئۈچۈن [ئابىدە پىلانى] (https://github.com/stjosh/auto_groups/milestones) نى كۆرۈڭ.",
    "Automatically add all users to these groups." : "بارلىق ئىشلەتكۈچىلەرنى بۇ گۇرۇپپىلارغا ئاپتوماتىك قوشۇڭ.",
    "Override Groups:" : "گۇرۇپپىلارنى قاپلاش:",
    "Users which are member of at least one of these groups are removed from the auto groups. This is also the case if the user is added to one of these groups after creation, i.e., membership in the override groups is checked after each group modification." : "بۇ گۇرۇپپىلارنىڭ ئاز دېگەندە بىر ئەزاسى بولغان ئابونتلار ئاپتوماتىك گۇرۇپپىدىن چىقىرىۋېتىلىدۇ. ئەگەر ئىشلەتكۈچى قۇرۇلغاندىن كېيىن بۇ گۇرۇپپىلارنىڭ بىرىگە قوشۇلسا ، يەنى ھەر بىر گۇرۇپپا ئۆزگەرتىلگەندىن كېيىن قاپلاپ كەتكەن گۇرۇپپىلارغا ئەزالىق تەكشۈرۈلىدۇ.",
    "Set Auto Group membership on user creation." : "ئىشلەتكۈچى قۇرۇشتا ئاپتوماتىك گۇرۇپپا ئەزالىقىنى بەلگىلەڭ.",
    "If checked, Auto Group membership will be enforced on user creation." : "تەكشۈرۈلسە ، ئاپتوماتىك گۇرۇپپا ئەزالىرى ئىشلەتكۈچى قۇرۇشتا ئىجرا قىلىنىدۇ.",
    "Check Auto Group membership on modification of a user's groups." : "ئىشلەتكۈچى گۇرۇپپىسىنىڭ ئۆزگەرتىلگەنلىكىنى ئاپتوماتىك گۇرۇپپا ئەزالىقىنى تەكشۈرۈڭ.",
    "If checked, Auto Group membership will be re-enforced for a user account every time it is added to or removed from a group." : "تەكشۈرۈلسە ، ھەر قېتىم گۇرۇپپىغا قوشۇلغان ياكى چىقىرىۋېتىلگەندە ئىشلەتكۈچى گۇرۇپپىسىنىڭ ھېساباتىغا ئاپتوماتىك گۇرۇپپا ئەزالىقى قايتا ئىجرا قىلىنىدۇ.",
    "Check for correct Auto Group membership on every login." : "ھەر بىر كىرىشتە ئاپتوماتىك گۇرۇپپا ئەزالىقىنى تەكشۈرۈڭ.",
    "Enable this setting to enforce proper Auto Group membership on every successful login. This is useful if either users are not created in Nextcloud (e.g., with external user backends) or to enforce correct group membership for all users when the Auto Groups / Override Groups have changed." : "بۇ تەڭشەكنى ھەر بىر مۇۋەپپەقىيەتلىك كىرىشتە مۇۋاپىق ئاپتوماتىك گۇرۇپپا ئەزالىقىنى ئىجرا قىلىڭ. ئەگەر ئىشلەتكۈچىلەر Nextcloud دا قۇرۇلمىغان بولسا (مەسىلەن ، سىرتقى ئىشلەتكۈچى ئارقا سەھنىسى بىلەن) ياكى ئاپتوماتىك گۇرۇپپا / قاپلاش گۇرۇپپىسى ئۆزگەرگەندە بارلىق ئىشلەتكۈچىلەرگە توغرا گۇرۇپپا ئەزالىقىنى ئىجرا قىلىش پايدىلىق."
},
"nplurals=2; plural=(n != 1);");
